"""inital commit

Revision ID: 21462983c2a2
Revises: 834b1a697901
Create Date: 2024-07-14 23:35:23.427057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21462983c2a2'
down_revision = '834b1a697901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_duration', sa.Integer(), nullable=True),
    sa.Column('plan_domain_limit', sa.Integer(), nullable=True),
    sa.Column('plan_api_call_limit', sa.Integer(), nullable=True),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('plan_type', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plan_plan_name'), ['plan_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_plan_plan_type'), ['plan_type'], unique=True)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=120), nullable=False),
    sa.Column('customer_phone', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('token', sa.String(length=32), nullable=True),
    sa.Column('token_expiration', sa.DateTime(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('domain_count', sa.Integer(), nullable=True),
    sa.Column('api_call_count', sa.Integer(), nullable=True),
    sa.Column('api_call_limit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_customer_email'), ['customer_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_customer_name'), ['customer_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_customer_phone'), ['customer_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_plan_id'), ['plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_token'), ['token'], unique=True)

    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain_name', sa.String(length=120), nullable=False),
    sa.Column('domain_start_date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_domain_name'), ['domain_name'], unique=True)

    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sa.String(length=120), nullable=False),
    sa.Column('activity_msg', sa.String(length=150), nullable=False),
    sa.Column('activity_timestamp', sa.DateTime(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_activity_msg'), ['activity_msg'], unique=True)
        batch_op.create_index(batch_op.f('ix_activity_activity_name'), ['activity_name'], unique=True)
        batch_op.create_index(batch_op.f('ix_activity_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_domain_id'), ['domain_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_domain_id'))
        batch_op.drop_index(batch_op.f('ix_activity_customer_id'))
        batch_op.drop_index(batch_op.f('ix_activity_activity_name'))
        batch_op.drop_index(batch_op.f('ix_activity_activity_msg'))

    op.drop_table('activity')
    with op.batch_alter_table('domain', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_domain_name'))
        batch_op.drop_index(batch_op.f('ix_domain_customer_id'))

    op.drop_table('domain')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_token'))
        batch_op.drop_index(batch_op.f('ix_customer_plan_id'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_name'))
        batch_op.drop_index(batch_op.f('ix_customer_customer_email'))

    op.drop_table('customer')
    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_plan_type'))
        batch_op.drop_index(batch_op.f('ix_plan_plan_name'))

    op.drop_table('plan')
    # ### end Alembic commands ###
